---
- name: Restart Redis-Sentinel
  systemd: name=redis-sentinel state=restarted
  when: 
    - bootstrapped
    - inventory_hostname != groups['redis_cluster'][0]
    - inventory_hostname != groups['redis_cluster'][1] 
    - inventory_hostname != groups['redis_cluster'][2]
