---
- name: Restart Redis-Sentinel
  systemd: name=redis-sentinel state=restarted
  when: bootstrapped and inventory_hostname != groups['redis_cluster'][0] and inventory_hostname != groups['redis_cluster'][1] 
