---
- name: Add Redis-Server Config
  become: yes
  become_user: root
  template: src=redis-master.conf.j2 dest=/etc/redis/redis.conf
    owner=redis group=redis mode=0644
  when: inventory_hostname == groups['redis_cluster'][0]

- name: Add Redis-Slave Config
  become: yes
  become_user: root
  template: src=redis-slave.conf.j2 dest=/etc/redis/redis.conf
    owner=redis group=redis mode=0644
  when: inventory_hostname == groups['redis_cluster'][1]

- name: Add Redis-Slave Config
  become: yes
  become_user: root
  template: src=redis-slave.conf.j2 dest=/etc/redis/redis.conf
    owner=redis group=redis mode=0644
  when: inventory_hostname == groups['redis_cluster'][2]

- name: Add Sentinal Config
  become: yes
  become_user: root
  template: src=sentinel.conf.j2 dest=/etc/redis/sentinel.conf
    owner=redis group=redis mode=0644
  when: 
    - inventory_hostname != groups['redis_cluster'][0]
    - inventory_hostname != groups['redis_cluster'][1]
    - inventory_hostname != groups['redis_cluster'][2]
